# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

eval "$(thefuck --alias)"
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
